inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: disable
  Exclude:
    - bin/**/*
    - config/*
    - config/environments/*
    - config/initializers/**/*
    - config/locales/*
    - db/**/*
    - examples/*/bin/**/*
    - examples/*/config/**/*
    - log/**/*
    - node_modules/**/*
    - spec/dummy/db/**/*
    - tmp/**/*
    - vendor/**/*

#############################################################################
# Gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false

#############################################################################
# Layout

Layout/CaseIndentation:
  IndentOneStep: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

#############################################################################
# Metrics

Metrics/BlockLength:
  Exclude:
    - lib/active_intelligence/concerns/s3.rb

#############################################################################
# Rails

Rails/ReflectionClassName:
  Enabled: false

#############################################################################
# RSpec

RSpec/DescribeClass:
  Exclude:
    - spec/hygiene/**/*
    - spec/views/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  CustomTransform:
    OpenAI: openai
    OpenAIAdapter: openai_adapter

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

#############################################################################
# Style

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
