default: &base
  adapter: <%= :base %>

development:
  <<: *base

test:
  <<: *base

openai:
  adapter: openai
  access_token: <%= ENV.fetch('OPENAI_ACCESS_TOKEN') %>
  organization_id: <%= ENV.fetch('OPENAI_ORGANIZATION_ID')  %>
  model: gpt-4
