eleven_labs: &eleven_labs
  adapter: eleven_labs
  api_key: <%= ENV.fetch('ELEVEN_LABS_API_KEY') %>

charlie: &charlie
  <<: *eleven_labs
  voice_id: IKne3meq5aSn9XLyUdCD

development:
  <<: *charlie

test:
  adapter: mock
  path: spec/data/audio/mock.mp3
